package com.edu.dmgame.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHAPTER_COMMENT_ENTITY".
 */
public class ChapterCommentEntity {

    private Long id;
    private String aid;
    private String typeid;
    private String username;
    private String ip;
    private String ip1;
    private String ip2;
    private String ischeck;
    private String dtime;
    private String mid;
    private String bad;
    private String good;
    private String ftype;
    private String face;
    private String msg;
    private String cid;
    private String reid;
    private String topid;
    private String floor;
    private String reply;

    public ChapterCommentEntity() {
    }

    public ChapterCommentEntity(Long id) {
        this.id = id;
    }

    public ChapterCommentEntity(Long id, String aid, String typeid, String username, String ip, String ip1, String ip2, String ischeck, String dtime, String mid, String bad, String good, String ftype, String face, String msg, String cid, String reid, String topid, String floor, String reply) {
        this.id = id;
        this.aid = aid;
        this.typeid = typeid;
        this.username = username;
        this.ip = ip;
        this.ip1 = ip1;
        this.ip2 = ip2;
        this.ischeck = ischeck;
        this.dtime = dtime;
        this.mid = mid;
        this.bad = bad;
        this.good = good;
        this.ftype = ftype;
        this.face = face;
        this.msg = msg;
        this.cid = cid;
        this.reid = reid;
        this.topid = topid;
        this.floor = floor;
        this.reply = reply;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAid() {
        return aid;
    }

    public void setAid(String aid) {
        this.aid = aid;
    }

    public String getTypeid() {
        return typeid;
    }

    public void setTypeid(String typeid) {
        this.typeid = typeid;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getIp1() {
        return ip1;
    }

    public void setIp1(String ip1) {
        this.ip1 = ip1;
    }

    public String getIp2() {
        return ip2;
    }

    public void setIp2(String ip2) {
        this.ip2 = ip2;
    }

    public String getIscheck() {
        return ischeck;
    }

    public void setIscheck(String ischeck) {
        this.ischeck = ischeck;
    }

    public String getDtime() {
        return dtime;
    }

    public void setDtime(String dtime) {
        this.dtime = dtime;
    }

    public String getMid() {
        return mid;
    }

    public void setMid(String mid) {
        this.mid = mid;
    }

    public String getBad() {
        return bad;
    }

    public void setBad(String bad) {
        this.bad = bad;
    }

    public String getGood() {
        return good;
    }

    public void setGood(String good) {
        this.good = good;
    }

    public String getFtype() {
        return ftype;
    }

    public void setFtype(String ftype) {
        this.ftype = ftype;
    }

    public String getFace() {
        return face;
    }

    public void setFace(String face) {
        this.face = face;
    }

    public String getMsg() {
        return msg;
    }

    public void setMsg(String msg) {
        this.msg = msg;
    }

    public String getCid() {
        return cid;
    }

    public void setCid(String cid) {
        this.cid = cid;
    }

    public String getReid() {
        return reid;
    }

    public void setReid(String reid) {
        this.reid = reid;
    }

    public String getTopid() {
        return topid;
    }

    public void setTopid(String topid) {
        this.topid = topid;
    }

    public String getFloor() {
        return floor;
    }

    public void setFloor(String floor) {
        this.floor = floor;
    }

    public String getReply() {
        return reply;
    }

    public void setReply(String reply) {
        this.reply = reply;
    }

}
