package com.edu.dmgame.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHAPTER_ENTITY".
 */
public class ChapterEntity {

    private Long id;
    private String title;
    private String pubdate;
    private String senddate;
    private String shorttitle;
    private String typeid;
    private String writer;
    private String source;
    private String litpic;
    private String feedback;
    private String click;
    private String description;
    private String typename;
    private String arcurl;
    private String body;

    public ChapterEntity() {
    }

    public ChapterEntity(Long id) {
        this.id = id;
    }

    public ChapterEntity(Long id, String title, String pubdate, String senddate, String shorttitle, String typeid, String writer, String source, String litpic, String feedback, String click, String description, String typename, String arcurl, String body) {
        this.id = id;
        this.title = title;
        this.pubdate = pubdate;
        this.senddate = senddate;
        this.shorttitle = shorttitle;
        this.typeid = typeid;
        this.writer = writer;
        this.source = source;
        this.litpic = litpic;
        this.feedback = feedback;
        this.click = click;
        this.description = description;
        this.typename = typename;
        this.arcurl = arcurl;
        this.body = body;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPubdate() {
        return pubdate;
    }

    public void setPubdate(String pubdate) {
        this.pubdate = pubdate;
    }

    public String getSenddate() {
        return senddate;
    }

    public void setSenddate(String senddate) {
        this.senddate = senddate;
    }

    public String getShorttitle() {
        return shorttitle;
    }

    public void setShorttitle(String shorttitle) {
        this.shorttitle = shorttitle;
    }

    public String getTypeid() {
        return typeid;
    }

    public void setTypeid(String typeid) {
        this.typeid = typeid;
    }

    public String getWriter() {
        return writer;
    }

    public void setWriter(String writer) {
        this.writer = writer;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getLitpic() {
        return litpic;
    }

    public void setLitpic(String litpic) {
        this.litpic = litpic;
    }

    public String getFeedback() {
        return feedback;
    }

    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    public String getClick() {
        return click;
    }

    public void setClick(String click) {
        this.click = click;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTypename() {
        return typename;
    }

    public void setTypename(String typename) {
        this.typename = typename;
    }

    public String getArcurl() {
        return arcurl;
    }

    public void setArcurl(String arcurl) {
        this.arcurl = arcurl;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

}
