package com.edu.dmgame.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GAME_CONTENT_ENTITY".
 */
public class GameContentEntity {

    private Long id;
    private String title;
    private String pubdate;
    private String senddate;
    private String shorttitle;
    private String typeid;
    private String writer;
    private String source;
    private String litpic;
    private String feedback;
    private String click;
    private String description;
    private String typename;
    private String arcurl;
    private String body;
    private String game_trans_name;
    private String release_date;
    private String language;
    private String terrace;
    private String made_company;
    private String release_company;
    private String websit;
    private String gameplay;
    private String graphics;
    private String sound;
    private String concept;
    private String multiplayer;
    private String total;
    private String game_info;
    private String system;
    private String system1;
    private String game_bbs;
    private String game_othername1;
    private String game_othername2;

    public GameContentEntity() {
    }

    public GameContentEntity(Long id) {
        this.id = id;
    }

    public GameContentEntity(Long id, String title, String pubdate, String senddate, String shorttitle, String typeid, String writer, String source, String litpic, String feedback, String click, String description, String typename, String arcurl, String body, String game_trans_name, String release_date, String language, String terrace, String made_company, String release_company, String websit, String gameplay, String graphics, String sound, String concept, String multiplayer, String total, String game_info, String system, String system1, String game_bbs, String game_othername1, String game_othername2) {
        this.id = id;
        this.title = title;
        this.pubdate = pubdate;
        this.senddate = senddate;
        this.shorttitle = shorttitle;
        this.typeid = typeid;
        this.writer = writer;
        this.source = source;
        this.litpic = litpic;
        this.feedback = feedback;
        this.click = click;
        this.description = description;
        this.typename = typename;
        this.arcurl = arcurl;
        this.body = body;
        this.game_trans_name = game_trans_name;
        this.release_date = release_date;
        this.language = language;
        this.terrace = terrace;
        this.made_company = made_company;
        this.release_company = release_company;
        this.websit = websit;
        this.gameplay = gameplay;
        this.graphics = graphics;
        this.sound = sound;
        this.concept = concept;
        this.multiplayer = multiplayer;
        this.total = total;
        this.game_info = game_info;
        this.system = system;
        this.system1 = system1;
        this.game_bbs = game_bbs;
        this.game_othername1 = game_othername1;
        this.game_othername2 = game_othername2;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPubdate() {
        return pubdate;
    }

    public void setPubdate(String pubdate) {
        this.pubdate = pubdate;
    }

    public String getSenddate() {
        return senddate;
    }

    public void setSenddate(String senddate) {
        this.senddate = senddate;
    }

    public String getShorttitle() {
        return shorttitle;
    }

    public void setShorttitle(String shorttitle) {
        this.shorttitle = shorttitle;
    }

    public String getTypeid() {
        return typeid;
    }

    public void setTypeid(String typeid) {
        this.typeid = typeid;
    }

    public String getWriter() {
        return writer;
    }

    public void setWriter(String writer) {
        this.writer = writer;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getLitpic() {
        return litpic;
    }

    public void setLitpic(String litpic) {
        this.litpic = litpic;
    }

    public String getFeedback() {
        return feedback;
    }

    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }

    public String getClick() {
        return click;
    }

    public void setClick(String click) {
        this.click = click;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getTypename() {
        return typename;
    }

    public void setTypename(String typename) {
        this.typename = typename;
    }

    public String getArcurl() {
        return arcurl;
    }

    public void setArcurl(String arcurl) {
        this.arcurl = arcurl;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getGame_trans_name() {
        return game_trans_name;
    }

    public void setGame_trans_name(String game_trans_name) {
        this.game_trans_name = game_trans_name;
    }

    public String getRelease_date() {
        return release_date;
    }

    public void setRelease_date(String release_date) {
        this.release_date = release_date;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getTerrace() {
        return terrace;
    }

    public void setTerrace(String terrace) {
        this.terrace = terrace;
    }

    public String getMade_company() {
        return made_company;
    }

    public void setMade_company(String made_company) {
        this.made_company = made_company;
    }

    public String getRelease_company() {
        return release_company;
    }

    public void setRelease_company(String release_company) {
        this.release_company = release_company;
    }

    public String getWebsit() {
        return websit;
    }

    public void setWebsit(String websit) {
        this.websit = websit;
    }

    public String getGameplay() {
        return gameplay;
    }

    public void setGameplay(String gameplay) {
        this.gameplay = gameplay;
    }

    public String getGraphics() {
        return graphics;
    }

    public void setGraphics(String graphics) {
        this.graphics = graphics;
    }

    public String getSound() {
        return sound;
    }

    public void setSound(String sound) {
        this.sound = sound;
    }

    public String getConcept() {
        return concept;
    }

    public void setConcept(String concept) {
        this.concept = concept;
    }

    public String getMultiplayer() {
        return multiplayer;
    }

    public void setMultiplayer(String multiplayer) {
        this.multiplayer = multiplayer;
    }

    public String getTotal() {
        return total;
    }

    public void setTotal(String total) {
        this.total = total;
    }

    public String getGame_info() {
        return game_info;
    }

    public void setGame_info(String game_info) {
        this.game_info = game_info;
    }

    public String getSystem() {
        return system;
    }

    public void setSystem(String system) {
        this.system = system;
    }

    public String getSystem1() {
        return system1;
    }

    public void setSystem1(String system1) {
        this.system1 = system1;
    }

    public String getGame_bbs() {
        return game_bbs;
    }

    public void setGame_bbs(String game_bbs) {
        this.game_bbs = game_bbs;
    }

    public String getGame_othername1() {
        return game_othername1;
    }

    public void setGame_othername1(String game_othername1) {
        this.game_othername1 = game_othername1;
    }

    public String getGame_othername2() {
        return game_othername2;
    }

    public void setGame_othername2(String game_othername2) {
        this.game_othername2 = game_othername2;
    }

}
